site_name: Sistema Hospitalar — Documentación
docs_dir: docs
strict: true

nav:
  - Inicio: index.md
  - Técnico:
      - Prompt Maestro: 01-tecnico/Prompt-Maestro-Sistema-Hospitalar.md
  - Negocio:
      - Documento de Negocio: 02-negocio/Documento-de-Negocio.md
  - MVP y Roadmap:
      - Resumen MVP1/MVP2: 03-mvp/Resumen-MVP1-MVP2.md
  - Discovery:
      - Jornadas y Mapa de Usuario: 04-discovery/Jornadas-y-Mapa-de-Usuario.md
  - Modelo de Datos:
      - Modelo ER textual: 05-modelo-datos/Modelo-ER-Textual.md
  - Manuales:
      - Manual Médicos y Recepcionistas: 06-manual-uso/Manual-Medicos-Recepcionistas.md
  - Privacidad:
      - Política de Protección de Datos: 07-privacidad/Politica-Proteccion-de-Datos.md
  - Gobernanza:
      - Manual de Actualización (Git): 00-gobernanza/Manual-Actualizacion-Git.md

theme:
  name: material

markdown_extensions:
  - admonition
  - tables
  - toc:
      permalink: true
