site_name: Sistema Hospitalar — Documentación
nav:
  - Inicio: index.md
  - Técnico:
      - Prompt Maestro: docs/01-tecnico/Prompt-Maestro-Sistema-Hospitalar.md
  - Negocio:
      - Documento de Negocio: docs/02-negocio/Documento-de-Negocio.md
  - MVP y Roadmap:
      - Resumen MVP1/MVP2: docs/03-mvp/Resumen-MVP1-MVP2.md
  - Discovery:
      - Jornadas y Mapa de Usuario: docs/04-discovery/Jornadas-y-Mapa-de-Usuario.md
  - Modelo de Datos:
      - Modelo ER textual: docs/05-modelo-datos/Modelo-ER-Textual.md
  - Manuales:
      - Manual Médicos y Recepcionistas: docs/06-manual-uso/Manual-Medicos-Recepcionistas.md
  - Privacidad:
      - Política de Protección de Datos: docs/07-privacidad/Politica-Proteccion-de-Datos.md
theme:
  name: material
markdown_extensions:
  - admonition
  - tables
  - toc:
      permalink: true
